In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('areas_prices.csv')
df

areas  prices
0   2600  550000
1   3000  565000
2   3200  610000
3   3600  680000
4   4000  725000

In [9]:
model=linear_model.LinearRegression()
model.fit(df[['areas']],df.prices)

LinearRegression()

In [11]:
model.predict([[5000]])

array([859554.79452055])

In [6]:
import pickle


In [12]:
with open('model_pickel','wb') as f:
    pickle.dump(model,f)

In [14]:
with open('model_pickel','rb') as f:
    mp=pickle.load(f)

In [16]:
mp.predict([[5000]])

array([859554.79452055])

In [19]:
 import joblib

In [20]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [21]:
mj=joblib.load('model_joblib')

In [22]:
mj.predict([[5000]])

array([859554.79452055])